apiVersion: v1
kind: Service
metadata:
  name: scorchedearth
  labels:
    app: scorchedearth
spec:
  type: NodePort
  ports:
  - port: 29008
    targetPort: 32008
    nodePort: 32008
    protocol: UDP
    name: sea-client-udp
  - port: 29009
    targetPort: 32009
    nodePort: 32009
    protocol: UDP
    name: sea-srv-udp
  - port: 29010
    targetPort: 32010
    nodePort: 32010
    protocol: UDP
    name: sea-steam-udp
  - port: 29011
    targetPort: 32011
    nodePort: 32011
    protocol: TCP
    name: sea-rcon-udp
  selector:
    app: scorchedearth
