apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - AllowedCheaterSteamIDs.txt
  - PlayersExclusiveJoinList.txt
  - PlayersJoinNoCheck.txt
  name: player-lists
  options:
    disableNameSuffixHash: true
- files:
  - main.cfg
  name: arkmanager-main-cfg
  options:
    disableNameSuffixHash: true
secretGenerator:
- envs:
  - ark-server-secrets.env
  name: server-secrets
  options:
    disableNameSuffixHash: true
namespace: ark
