apiVersion: v1
kind: Service
metadata:
  name: thecenter
  labels:
    app: thecenter
spec:
  type: NodePort
  ports:
  - port: 29004
    targetPort: 32004
    nodePort: 32004
    protocol: UDP
    name: ctr-client-udp
  - port: 29005
    targetPort: 32005
    nodePort: 32005
    protocol: UDP
    name: ctr-srv-udp
  - port: 29006
    targetPort: 32006
    nodePort: 32006
    protocol: UDP
    name: ctr-steam-udp
  - port: 29007
    targetPort: 32007
    nodePort: 32007
    protocol: TCP
    name: ctr-rcon-udp
  selector:
    app: thecenter
