---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ark-user-rb
subjects:
  - kind: ServiceAccount
    name: ark-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ark-user-general-access
