apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ark-pvc.yaml
- ./ark-service.yaml
- ./ark-statefulset.yaml
secretGenerator:
- envs:
  - valguero-secrets.env
  name: valguero-secrets
  options:
    disableNameSuffixHash: true
namespace: ark
