apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: extinction
  labels:
    app: extinction
spec:
  replicas: 1
  serviceName: extinction
  selector:
    matchLabels:
      app: extinction
  template:
    metadata:
      labels:
        app: extinction
    spec:
      containers:
      - image: nhalase/ark
        imagePullPolicy: Always
        name: extinction
        resources:
          requests:
            cpu: 2000m
            memory: 12Gi
        env:
          - name: SESSIONNAME
            value: Extinction
          - name: CLIENTPORT
            value: "32020"
          - name: SERVERPORT
            value: "32021"
          - name: STEAMPORT
            value: "32022"
          - name: RCONPORT
            value: "32023"
          - name: SERVERMAP
            value: Extinction # TheIsland, TheCenter, ScorchedEarth_P, Ragnarok, Aberration_P, Extinction, Valguero_P, Genesis, CrystalIsles, LostIsland, Fjordur
          - name: SERVERPASSWORD
            valueFrom:
              secretKeyRef:
                name: server-secrets
                key: SERVERPASSWORD
          - name: ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: server-secrets
                key: ADMINPASSWORD
          - name: TZ
            valueFrom:
              secretKeyRef:
                name: extinction-secrets
                key: TZ
        ports:
          - containerPort: 32020
            protocol: UDP
            name: ext-client-udp
          - containerPort: 32021
            protocol: UDP
            name: ext-server-udp
          - containerPort: 32022
            protocol: UDP
            name: ext-steam-udp
          - containerPort: 32023
            protocol: TCP
            name: ext-rcon-tcp
        volumeMounts:
          - name: extinction-persistent-storage
            mountPath: /ark
          - name: arkmanager-main-cfg-volume
            mountPath: /etc/arkmanager/instances/main.cfg
            subPath: main.cfg
      # Use an init container to help prepare some config files before the main container starts
      initContainers:
        - name: extinction-prep-container
          image: busybox
          volumeMounts:
            - name: extinction-persistent-storage
              mountPath: /ark
            - name: extinction-config-volume
              mountPath: /ark-config
          command: ['sh', '-c']
          args:
            - rm -f /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              mkdir -p /ark/server/ShooterGame/Saved/Config/LinuxServer;
              cd /ark;
              ln -s /ark-config/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt;
              mkdir -p /ark/server/ShooterGame/Binaries/Linux/;
              ln -s /ark-config/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt;
              ln -s /ark-config/PlayersExclusiveJoinList.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              chown -R 10000:10001 /ark
      volumes:
        - name: extinction-persistent-storage
          persistentVolumeClaim:
            claimName: extinction
        - name: extinction-config-volume
          projected:
            sources:
              - configMap:
                  name: player-lists
        - name: arkmanager-main-cfg-volume
          configMap:
            name: arkmanager-main-cfg
