apiVersion: v1
kind: Service
metadata:
  name: aberration
  labels:
    app: aberration
spec:
  type: NodePort
  ports:
  - port: 29016
    targetPort: 32016
    nodePort: 32016
    protocol: UDP
    name: abe-client-udp
  - port: 29017
    targetPort: 32017
    nodePort: 32017
    protocol: UDP
    name: abe-srv-udp
  - port: 29018
    targetPort: 32018
    nodePort: 32018
    protocol: UDP
    name: abe-steam-udp
  - port: 29019
    targetPort: 32019
    nodePort: 32019
    protocol: TCP
    name: abe-rcon-udp
  selector:
    app: aberration
