name: "Quality Check"
permissions: {}

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  shellcheck:
    name: "Shellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Run ShellCheck"
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            Dockerfile
            crontab
            main.cfg
